name: check_parser
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  dev: ^1.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^2.1.3
  go_router: ^6.0.3
  riverpod: ^2.1.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  dio: ^4.0.6
  regexed_validator: ^2.0.0+1
  hive: ^2.2.3
  path_provider: ^2.0.12
  hooks_riverpod: ^2.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter  
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.2.0
  hive_generator: ^2.0.0
  

flutter:
  uses-material-design: true